Fix dedendum calculation
gumyr/bd_warehouse pull request #39
Opened 2024-12-13 13:37 UTC by smurfix

Closes #38.

2024-12-13 13:39 UTC, smurfix commented
Tested with various gear ratios and modules.

2024-12-15 17:59 UTC, gumyr requested changes
Thank you for pointing this out - a pretty significant problem.

2024-12-15 17:59 UTC, gumyr commented on src/bd_warehouse/gear.py
> +            if (rp := r * cos(involute)) > self.root_radius:
I believe this check will always pass as `r` is at least the `base_radius`.

2024-12-15 17:59 UTC, gumyr commented on src/bd_warehouse/gear.py
> +            if root_fillet:
Nice.  I'm not sure one would want to actually create a gear without a root fillet but there doesn't seem to be a reason to force it.

2024-12-15 17:59 UTC, gumyr commented on src/bd_warehouse/gear.py
> +            else (1.2*module + root_fillet)
After reviewing this it seems like the value should just be `1.25 * module` - where `1.25` is supposedly a common value.  The `root_fillet` won't interfere unless very large values are used.

2024-12-15 18:25 UTC, smurfix commented on src/bd_warehouse/gear.py
> +            if (rp := r * cos(involute)) > self.root_radius:
It doesn't. See the second image in my bug report. Or simply create a gear with 100 teeth, which will crash trying to do the root fillet, which is how I found that problem.

2024-12-15 18:26 UTC, smurfix commented on src/bd_warehouse/gear.py
> +            else (1.2*module + root_fillet)
That should work too. Will change.

2024-12-16 23:57 UTC, merged

2024-12-16 23:58 UTC, gumyr commented
Thanks!  The 100 tooth gear is really an invalid gear specification - normally a pressure angle of 20 degrees are used for these high tooth count gears.

2024-12-17 08:38 UTC, smurfix commented
Might be a good idea to emit a warning then. "Insufficient gear depth - increase pressure angle"?